@extends('admin-panel.master')

@section('title','dashboard')

@section('content')

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero totam cum delectus aliquid! Placeat maiores atque veritatis mollitia dolore sequi libero labore dolorem! Nihil quas corrupti esse. Provident, ab ullam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae iure voluptates sint illum aliquam possimus architecto necessitatibus dolore quidem provident quos accusantium sit minima cupiditate ullam non perferendis, dolorum aperiam!</p>

@endsection
